apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  labels:
    app: grafana
spec:
  ports:
  - port: 3000
    name: grafana
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer
  loadBalancerIP: 192.168.99.150

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana_image
        name: grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000